### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jeremylong/DependencyCheck#2040]
Hi
The following lines have cryptographic API misuses. <br> File name => utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java: Line number => 148: API name => MessageDigest:<BR> File name => utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java: Line number => 95: API name => MessageDigest:<BR> File name => utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java: Line number => 148: API name => MessageDigest:<BR> File name => utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java: Line number => 231: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => utils/src/main/java/org/owasp/dependencycheck/utils/Checksum.java: Line number => 82: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by jeremylong** [comment]
This is not used in a security critical context.
