### ISSUE TITLE
Dependencies in build.gradle files

### ISSUE THREAD

**Issue by sporykhin** [jeremylong/DependencyCheck#2747]
Hi
I`m trying to figure out is the checker (gradle version) scans dependencies described in build.gradle files?
Looks like the task scans only jar files in local folders and don't download or do something with deps. Am I right?

Thanks in advance!

**Comment by jeremylong** [comment]
You are correct if you are using the CLI (or docker) version of dependency-check.  However, we recommend you use the gradle plugin: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html

**Comment by sporykhin** [comment]
@jeremylong 
Thanks for your quick response!
I already switched to a gradle plugin and still no luck with dependencies resolution. Do I need some extra arguments, maybe?

Project written in kotlin, dependencies fixed in build.gradle file like this 

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
}

I cant see any log entry about deps resolution

**Comment by jeremylong** [comment]
Can you post how you've configured dependency-check?

**Comment by sporykhin** [comment]
Found my mistake
I have to use :dependencyCheckAggregate cause its multi-project

Sorry
