### ISSUE TITLE
dependecy-check:latest based on outdated alpine image

### ISSUE THREAD

**Issue by sporykhin** [jeremylong/DependencyCheck#3879]
Looks like current image based on Alpine 3.12

❯ docker run -it --rm --entrypoint="" owasp/dependency-check cat /etc/os-release
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.7
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by sporykhin** [comment]
is it possible to update to 3.14?

**Comment by jeremylong** [comment]
https://github.com/jeremylong/DependencyCheck/pull/3831
